### ISSUE TITLE
i3-style completely non-functional

### ISSUE THREAD

**Issue by Portadiam** [acrisci/i3-style#13]
On Ubuntu 14.10 with vanilla (non-gaps) i3 installed, i3-styles doesn't modify the config file at all nor does it display any output nor errors no matter what arguments are given to it.

**Comment by acrisci** [comment]
Does it display usage info with no args?

**Comment by Portadiam** [comment]
Nope. Zero output.

    ~$ i3-style
    ~$

**Comment by acrisci** [comment]
It seems to be working fine for me on archlinux. I can look into this in a few days when I have time to set up a VM. If you want to take a look at it before then, go ahead.

Can you try the development version with `npm install i3-style` and then running `src/cli.coffee` or running `cake build` and then running `lib/cli.js`? That might tell me that the cause is either with npm or the build.

**Comment by Portadiam** [comment]
Got it running.
Started displaying errors when I tried to run the cloned version as suggested, I was missing the node dependencies: shelljs, commander, js-yaml, and color-namer.
The version installed from npm still doesn't work, but the cloned one does, so I think it is an installation problem.
Thank you for the help.

**Comment by acrisci** [comment]
Does code show up when you type `cat $(which i3-style)`?

**Comment by Portadiam** [comment]
Yes. Begins with:

    #!/usr/bin/env node
    // Generated by CoffeeScript 1.7.1
    var HOME, VERSION, config, configPath, exitWithError, fileExists, fs, i3Path, mkConfig, mkTheme, outputPath, pathUtil, program, sh, theme, themesAvailable, themesDir, themesList, tmpConfigPath, tmpPath, tmpdir, validation, yaml, yamlTheme, _, _ref, _ref1, __indexOf = [].indexOf || function(item) {  for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

**Comment by acrisci** [comment]
That should run the binary at `node`.

What do you get when you type `node --version`?

**Comment by Portadiam** [comment]
No output. Problem solved: my node installation is what was at fault. Reinstalled node and it now works.
Thanks for the help!

**Comment by acrisci** [comment]
It seems like this is a known bug with ubuntu that they have recently fixed. For anyone else affected by this, just put a symlink from `/usr/bin/nodejs` to `/usr/bin/node` and it should work.
