### ISSUE TITLE
Commandline option doesn't work like it is documented

### ISSUE THREAD

**Issue by okraits** [acrisci/i3-style#15]
*i3-style* shows the following usage:

> Usage: i3-style \<theme> [options]
> -o, --output \<file>    Apply the theme, attempt to validate the result, and write it to \<file>. Print to STDOUT if no output file is given.

So you would assume that *i3-style base16-tomorrow -o* would print the result to STDOUT. But it doesn't - instead, it triggers the following error:

> error: option `-o, --output \<file>' argument missing

How can we solve this issue?

**Comment by acrisci** [comment]
Hey, sorry for the late reply. I seem to have missed this issue somehow.

Simply running `i3-style base16-tomorrow` will print to stdout. The `-o` switch is for specifying a file to write to. This is primarily for safety reasons. It will do validation before writing to the file.

But you are right that it is worded in an ambiguous way. What I meant to say was that it will print to STDOUT if `-o` is not given at all, not given with no argument.

I will fix this to make that more clear.

**Comment by acrisci** [comment]
Fixed it.

Thanks. You are the best :+1: .

**Comment by okraits** [comment]
Thank you :+1:
