### ISSUE TITLE
When I run "i3-style solarized -o ~/.config/i3/config --reload", I get this error:

### ISSUE THREAD

**Issue by nickcorona** [acrisci/i3-style#31]
/usr/bin/env: ‘node’: No such file or directory

**Comment by nickcorona** [comment]
This solved my issue:

http://stackoverflow.com/questions/26320901/cannot-install-nodejs-usr-bin-env-node-no-such-file-or-directory

**Comment by acrisci** [comment]
I don't know if there's anything I can do to fix this in my program for better user experience.

**Comment by Hammer2900** [comment]
![image](https://user-images.githubusercontent.com/2808302/51327319-ba459c80-1a79-11e9-9783-865af06ec2c4.png)

have error when run program to =(

**Comment by acrisci** [comment]
That's another issue. The error message should be better. But I think there's no theme at `themes/ubuntu`.
