### ISSUE TITLE
npm packet not including commit daa5f06 - wrong color on solarized theme

### ISSUE THREAD

**Issue by roboter202** [acrisci/i3-style#33]
Hey I applied the solarized theme but the script generates

`client.focused #859900 #859900 #fdf6e3 #859900`

though the indicator color is supposed to be violet (#6c71c4) not green (#859900)

i3style was installed using npm only minutes ago.

I've look into this and it seems the theme shipped via npm is not including the changes from commit 
[daa5f06](https://github.com/acrisci/i3-style/commit/daa5f06151d9b228ee5a988f6bdb3e6cce918e38) from March '16

You may want to update the npm packet

**Comment by acrisci** [comment]
Sure, will update soon.

**Comment by acrisci** [comment]
https://github.com/acrisci/i3-style/releases/tag/v0.10.0
