### ISSUE TITLE
FR: ignore commented-out color settings

### ISSUE THREAD

**Issue by laur89** [acrisci/i3-style#40]
It'd be cool if `i3-style` wouldn't remove commented out color setting from the config files.
Perhaps it should also ignore lines that start with whitespace to make sure it doesn't touch other scoped items? Eg script atm affects this block:

```# bar {      
#          
#           colors {
#               separator          #161615
#               background         #020202
#               statusline         #111111
#              
#               # Bar colors       border    background    text 
#               focused_workspace  #07090d   #020202       #5E468C
#               active_workspace   #07090d   #020202       #268bd2
#               inactive_workspace #07090d   #020202       #899CA1
#               urgent_workspace   #07090d   #020202       #287373
#          }
# }

**Comment by acrisci** [comment]
Sorry I'm getting to this really late. Yeah this should be addressed. Watch #38 which is a rewrite that should fix this. I hope I can get around to finishing it.
